
const playersData = {
    
    'Chennai Super Kings': [
      { name: 'Ruturaj Gaikwad (c)', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/102.png", role: "Batsman" },
      { name: 'MS Dhoni', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/57.png", role: "Wicketkeeper-Batsman" },
      { name: 'Matheesha Pathirana', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1014.png", role: "Bowler" },
      { name: 'Shivam Dube', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/211.png", role: "All-rounder" },
      { name: 'Noor Ahmad', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/975.png", role: "Bowler" },
      { name: 'Ravichandran Ashwin', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/45.png", role: "All-rounder" },
      { name: 'Devon Conway', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/601.png", role: "Batsman" },
      { name: 'Rachin Ravindra', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/724.png", role: "All-rounder" },
      { name: 'Rahul Tripathi', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/188.png", role: "Batsman" },
      { name: 'Khaleel Ahmad', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/8.png", role: "Bowler" },
      { name: 'Mukesh Choudhary', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/970.png", role: "Bowler" },
      { name: 'Shreyas Gopal', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/192.png", role: "Bowler" },
      { name: 'Vijay Shankar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/192.png", role: "All-rounder" },
      { name: 'Nathan Ellis', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/633.png", role: "Bowler" },
      { name: 'Gurjapneet Singh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/2256.png", role: "Bowler" },
      { name: 'Ravindra Jadeja', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/46.png", role: "All-rounder" },
      { name: 'Sam Curran', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/138.png", role: "All-rounder" },
      { name: 'Anshul Kamboj', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3106.png", role: "Bowler" },
      { name: 'Deepak Hooda', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/215.png", role: "All-rounder" },
      { name: 'Jamie Overton', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1216.png", role: "All-rounder" },
      { name: 'Kamlesh Nagarkoti', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/146.png", role: "Bowler" },
      { name: 'Ramakrishan Ghosh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3559.png", role: "Batsman" },
      { name: 'Andre Siddarth', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3157.png", role: "Bowler" },
      { name: 'Vansh Bedi', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3558.png", role: "Bowler" },
      { name: 'Shaik Rasheed', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/778.png", role: "Batsman" }
    ],

    'Delhi Capitals': [
  { "name": "Axar Patel (c)", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/110.png", "role": "All-rounder" }, 
  { "name": "KL Rahul", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/19.png", "role": "Wicketkeeper-Batsman" },
  { "name": "Jake Fraser", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3115.png", "role": "Batsman" },
  { "name": "Karun Nair", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/131.png", "role": "Batsman" },
  { "name": "Faf Du Plessis", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/94.png", "role": "Batsman" },
  { "name": "Donovan Ferreira", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/2033.png", "role": "Wicketkeeper-Batsman" },
  { "name": "Abhishek Porel", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1580.png", "role": "Wicketkeeper-Batsman" },
  { "name": "Tristan Stubbs", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1017.png", "role": "Batsman" },
  { "name": "Sameer Rizvi", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1229.png", "role": "Batsman" },
  { "name": "Ashutosh Sharma", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3109.png", "role": "Batsman" },
  { "name": "Dharshan Nalkande", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/127.png", "role": "Bowler" },
  { "name": "Vipraj Nigam", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3560.png", "role": "Batsman" },
  { "name": "Ajay Mandal", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1931.png", "role": "All-rounder" },
  { "name": "Manvath Kumar", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3562.png", "role": "Bowler" },
  { "name": "Tirpurana Vijay", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3563.png", "role": "Bowler" },
  { "name": "Madhav Tiwari", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3561.png", "role": "Bowler" },
  { "name": "Mitchell Starc", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/31.png", "role": "Bowler" },
  { "name": "T. Natarajan", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/31.png", "role": "Bowler" },
  { "name": "Mohit Sharma", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/100.png", "role": "Bowler" },
  { "name": "Mukesh Kumar", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1462.png", "role": "Bowler" },
  { "name": "Dushmantha Chameera", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/608.png", "role": "Bowler" },
  { "name": "Kuldeep Yadav", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/14.png", "role": "Bowler" }
],
'Gujarat Titans': [
    { "name": "Shubman Gill (c)", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/62.png", "role": "Batsman" },
    { "name": "Josh Buttler", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/182.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Kumar Kushagra", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3101.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Anuj Rawat", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/534.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Sharfane Rutherford", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/122.png", "role": "All-Rounder" },
    { "name": "Glenn Phillips", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/635.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Nishant Sindhu", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/791.png", "role": "All-Rounder" },
    { "name": "Mahipal Lomror", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/184.png", "role": "All-Rounder" },
    { "name": "Washington Sundar", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/20.png", "role": "All-Rounder" },
    { "name": "Mohammed Arshad Khan", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/988.png", "role": "Bowler" },
    { "name": "R Sai Kishore", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/544.png", "role": "Bowler" },
    { "name": "Lalit Yadav", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/165.png", "role": "All-Rounder" },
    { "name": "Karim Janat", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/247.png", "role": "All-Rounder" },
    { "name": "Sai Sudharsan", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/976.png", "role": "Batsman" },
    { "name": "Shahrukh Khan", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/590.png", "role": "All-Rounder" },
    { "name": "Kagiso Rabada", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/116.png", "role": "Bowler" },
    { "name": "Mohammed Siraj", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/63.png", "role": "Bowler" },
    { "name": "Prasidh Krishna", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/150.png", "role": "Bowler" },
    { "name": "Manav Suthar", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/2443.png", "role": "Bowler" },
    { "name": "Gerald Coetzee", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/2535.png", "role": "Bowler" },
    { "name": "Harpreet Brar", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1231.png", "role": "Bowler" },
    { "name": "Ishant Sharma", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/50.png", "role": "Bowler" },
    { "name": "Kulwant Khejroliya", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/204.png", "role": "Bowler" },
    { "name": "Rahul Tewatia", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/120.png", "role": "All-Rounder" },
    { "name": "Rashid Khan", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/218.png", "role": "Bowler" }
],
'Kolkata Knight Riders': [
    { "name": "Ajinkya Rahane (c)", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/44.png", "role": "Batsman" },
    { "name": "Rinku Singh", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/152.png", "role": "Batsman" },
    { "name": "Quinton de Kock", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/170.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Rahmanullah Gurbaz", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/641.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Angkrish Raghuvanshi", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/787.png", "role": "Batsman" },
    { "name": "Rovman Powell", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/329.png", "role": "All-Rounder" },
    { "name": "Manish Pandey", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/16.png", "role": "Batsman" },
    { "name": "Luvnith Sisodia", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1009.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Venkatesh Iyer", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/584.png", "role": "All-Rounder" },
    { "name": "Anukul Roy", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/160.png", "role": "All-Rounder" },
    { "name": "Mayank Markande", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/87.png", "role": "Bowler" },
    { "name": "Spencer Johnson", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/2518.png", "role": "Bowler" },
    { "name": "Harshit Rana", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1013.png", "role": "Bowler" },
    { "name": "Moeen Ali", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/206.png", "role": "All-Rounder" },
    { "name": "Ramandeep Singh", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/991.png", "role": "All-Rounder" },
    { "name": "Andre Russell", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/141.png", "role": "All-Rounder" },
    { "name": "Sunil Narine", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/156.png", "role": "All-Rounder" },
    { "name": "Varun Chakravarthy", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/140.png", "role": "Bowler" },
    { "name": "Chetan Sakariya", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/592.png", "role": "Bowler" },
    { "name": "Anrich Nortje", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/142.png", "role": "Bowler" },
    { "name": "Vaibhav Arora", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/583.png", "role": "Bowler" }
],
'Lucknow Super Giants': [
    { "name": "Rishabh Pant", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/18.png", "role": "Wicketkeeper-Batsman" },
    { "name": "David Miller", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/128.png", "role": "Batsman" },
    { "name": "Aiden Markram", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/287.png", "role": "Batsman" },
    { "name": "Aryan Juyal", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/990.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Himmat Singh", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/203.png", "role": "Batsman" },
    { "name": "Mathew Breetzke", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/2805.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Nicholas Pooran", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/136.png", "role": "Wicketkeeper-Batsman" },
    { "name": "Mitchell Marsh", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/40.png", "role": "All-Rounder" },
    { "name": "Abdul Samad", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/525.png", "role": "Batsman" },
    { "name": "Shahbaz Ahmad", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/523.png", "role": "All-Rounder" },
    { "name": "Yuvraj Chaudhary", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3564.png", "role": "Batsman" },
    { "name": "Rajvardhan Hangargekar", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/783.png", "role": "Bowler" },
    { "name": "Arshin Kulkarni", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/2788.png", "role": "All-Rounder" },
    { "name": "Ayush Badoni", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/985.png", "role": "All-Rounder" },
    { "name": "Shardul Thakur", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/105.png", "role": "Bowler" },
    { "name": "Avesh Khan", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/109.png", "role": "Bowler" },
    { "name": "Akash Deep", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1007.png", "role": "Bowler" },
    { "name": "M. Sidharth", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/532.png", "role": "Bowler" },
    { "name": "Digvesh Singh", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3565.png", "role": "Bowler" },
    { "name": "Akash Singh", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/535.png", "role": "Bowler" },
    { "name": "Shamar Joseph", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/3105.png", "role": "Bowler" },
    { "name": "Prince Yadav", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/1225.png", "role": "All-Rounder" },
    { "name": "Mayank Yadav", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2024/987.png", "role": "Bowler" },
    { "name": "Ravi Bishnoi", "image": "https://documents.iplt20.com/ipl/IPLHeadshot2025/520.png", "role": "Bowler" }
],
'Mumbai Indians': [
      { name: 'Hardik Pandya', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/54.png", role: 'All-rounder' },
      { name: 'Rohit Sharma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/6.png", role: 'Batsman' },
      { name: 'Surya Kumar Yadav', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/174.png", role: 'Batsman' },
      { name: 'Robin Minz', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3103.png", role: 'Wicketkeeper-Batsman' },
      { name: 'Ryan Rikelton', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/743.png", role: 'Wicketkeeper-Batsman' },
      { name: 'Shrijith Krishnan', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3570.png", role: 'Wicketkeeper-Batsman' },
      { name: 'Bevon Jacobs', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3567.png", role: 'Batsman' },
      { name: 'Tilak Varma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/993.png", role: 'Batsman' },
      { name: 'Naman Dhir', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3107.png", role: 'Batsman' },
      { name: 'Will Jacks', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1941.png", role: 'All-rounder' },
      { name: 'Mitcheal Santner', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/75.png", role: 'All-rounder' },
      { name: 'Raj Angad Bawa', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/781.png", role: 'All-rounder' },
      { name: 'Vignesh Puthur', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3566.png", role: 'Batsman' },
      { name: 'Corbin Bosch', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1041.png", role: 'All-rounder' },
      { name: 'Trent Boult', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/66.png", role: 'Bowler' },
      { name: 'Karn Sharma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/98.png", role: 'Bowler' },
      { name: 'Deepak Chahar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/91.png", role: 'Bowler' },
      { name: 'Ashwani Kumar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3569.png", role: 'Bowler' },
      { name: 'Reece Topley', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/574.png", role: 'Bowler' },
      { name: 'V.Satyanarayana', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3568.png", role: 'Bowler' },
      { name: 'Arjun Tendulkar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/585.png", role: 'All-rounder' },
      { name: 'Mujeeb-ur-Rahman', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/134.png", role: 'Bowler' },
      { name: 'Jasprit Bumrah', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/9.png", role: 'Bowler' }
],
'Punjab Kings': [
        { name: 'Shreyas Iyer (c)', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/12.png", role: 'Batsman' },
        { name: 'Nehal Wadhera', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1541.png", role: 'Batsman' },
        { name: 'Vishnu Vinod', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/581.png", role: 'Wicketkeeper-Batsman' },
        { name: 'Josh Inglis', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/647.png", role: 'Wicketkeeper-Batsman' },
        { name: 'Harnoor Pannu', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/784.png", role: 'Batsman' },
        { name: 'Pyla Avinash', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3573.png", role: 'Batsman' },
        { name: 'Prabsimran Singh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/137.png", role: 'Wicketkeeper-Batsman' },
        { name: 'Shashank Singh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/191.png", role: 'All-rounder' },
        { name: 'Marcus Stoinis', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/23.png", role: 'All-rounder' },
        { name: 'Glenn Maxwell', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/28.png", role: 'All-rounder' },
        { name: 'Harpreet Brar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/130.png", role: 'All-rounder' },
        { name: 'Marco Jansen', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/586.png", role: 'Bowler' },
        { name: 'Azmatullah Omarzai', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1354.png", role: 'All-rounder' },
        { name: 'Priyansh Arya', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3571.png", role: 'Batsman' },
        { name: 'Aaron Hardie', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/2704.png", role: 'All-rounder' },
        { name: 'Musheer Khan', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/2813.png", role: 'All-rounder' },
        { name: 'Suryansh Shedge', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/2146.png", role: 'All-rounder' },
        { name: 'Arshdeep Singh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/125.png", role: 'Bowler' },
        { name: 'Yuzvendra Chahal', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/10.png", role: 'Bowler' },
        { name: 'Vyshak Vijaykumar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/2034.png", role: 'Bowler' },
        { name: 'Yash Thakur', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1550.png", role: 'Bowler' },
        { name: 'Lockie Ferguson', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/69.png", role: 'Bowler' },
        { name: 'Kuldeep Sen', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1005.png", role: 'Bowler' },
        { name: 'Xavier Bartlett', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3572.png", role: 'Bowler' },
        { name: 'Praveen Dubey', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/548.png", role: 'Bowler' }
],
'Rajasthan Royals': [
        { name: 'Sanju Samson (c)', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/190.png", role: 'Wicketkeeper-Batsman' },
        { name: 'Subham Dhubey', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3112.png", role: 'All-rounder' },
        { name: 'Vaibhav Suryavanshi', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3498.png", role: 'Batsman' },
        { name: 'Kunal Rathore', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1540.png", role: 'Wicketkeeper-Batsman' },
        { name: 'Shimron Hetmyer', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/210.png", role: 'Batsman' },
        { name: 'Yashasvi Jaiswal', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/533.png", role: 'Batsman' },
        { name: 'Dhruv Jurel', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1004.png", role: 'Wicketkeeper-Batsman' },
        { name: 'Riyan Parag', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/189.png", role: 'All-rounder' },
        { name: 'Nitish Rana', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/148.png", role: 'Batsman' },
        { name: 'Yudhvir Charak', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/587.png", role: 'All-rounder' },
        { name: 'Jofra Archer', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/181.png", role: 'Bowler' },
        { name: 'Maheesh Theekshana', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/629.png", role: 'Bowler' },
        { name: 'Wanindu Hasaranga', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/377.png", role: 'All-rounder' },
        { name: 'Akash Madhwal', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1045.png", role: 'Bowler' },
        { name: 'Kumar Kartikeya Singh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1015.png", role: 'Bowler' },
        { name: 'Tushar Deshpande', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/539.png", role: 'Bowler' },
        { name: 'Fazalhaq Farooqi', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1011.png", role: 'Bowler' },
        { name: 'Kwena Maphaka', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/801.png", role: 'Bowler' },
        { name: 'Ashok Sharma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/980.png", role: 'Bowler' },
        { name: 'Sandeep Sharma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/220.png", role: 'Bowler' }
],
'Sunrisers Hyderabad': [
      { name: 'Pat Cummins (c)', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/33.png", role: 'Bowler' },
      { name: 'Ishan Kishan', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/164.png", role: 'Wicketkeeper-Batsman' },
      { name: 'Atharva Taide', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1001.png", role: 'All-rounder' },
      { name: 'Abhinav Manohar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/974.png", role: 'Batsman' },
      { name: 'Aniket Varma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3576.png", role: 'Batsman' },
      { name: 'Sachin Baby', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/599.png", role: 'Batsman' },
      { name: 'Heinrich Klaasen', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/202.png", role: 'Wicketkeeper-Batsman' },
      { name: 'Travis Head', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/37.png", role: 'All-rounder' },
      { name: 'Harshal Patel', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/114.png", role: 'Bowler' },
      { name: 'Kamindu Mendis', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/627.png", role: 'All-rounder' },
      { name: 'Wiaan Mulder', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/630.png", role: 'All-rounder' },
      { name: 'Abhishek Sharma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/212.png", role: 'All-rounder' },
      { name: 'Nitish Kumar Reddy', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1944.png", role: 'All-rounder' },
      { name: 'Mohammad Shami', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/47.png", role: 'Bowler' },
      { name: 'Rahul Chahar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/171.png", role: 'Bowler' },
      { name: 'Adam Zampa', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/24.png", role: 'Bowler' },
      { name: 'Simarjeet Singh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/622.png", role: 'Bowler' },
      { name: 'Zeesan Ansari', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3575.png", role: 'Bowler' },
      { name: 'Jaydev Unadkat', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/180.png", role: 'Bowler' },
      { name: 'Eshan Malinga', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3339.png", role: 'Bowler' }
],
'Royal Challengers Bangalore': [
      { name: 'Rajat Patidar (c)', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/597.png", role: 'Batsman' },
      { name: 'Virat Kohli', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/2.png", role: 'Batsman' },
      { name: 'Phil Salt', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1220.png", role: 'Wicketkeeper-Batsman' },
      { name: 'Jitesh Sharma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1000.png", role: 'Wicketkeeper-Batsman' },
      { name: 'Devdutt Padikkal', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/200.png", role: 'Batsman' },
      { name: 'Swastik Chikara', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3102.png", role: 'Batsman' },
      { name: 'Liam Livingstone', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/183.png", role: 'All-rounder' },
      { name: 'Krunal Pandya', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/17.png", role: 'All-rounder' },
      { name: 'Swapnil Singh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1483.png", role: 'All-rounder' },
      { name: 'Tim David', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/636.png", role: 'All-rounder' },
      { name: 'Romario Shepherd', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/371.png", role: 'All-rounder' },
      { name: 'Manoj Bhandage', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1485.png", role: 'All-rounder' },
      { name: 'Jacob Bethell', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/869.png", role: 'All-rounder' },
      { name: 'Josh Hazlewood', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/36.png", role: 'Bowler' },
      { name: 'Rasikh Dar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/172.png", role: 'Bowler' },
      { name: 'Suyash Sharma', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1932.png", role: 'Bowler' },
      { name: 'Bhuvneshwar Kumar', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/15.png", role: 'Bowler' },
      { name: 'Nuwan Thushara', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/813.png", role: 'Bowler' },
      { name: 'Lungisani Ngidi', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/99.png", role: 'Bowler' },
      { name: 'Abhinandhan Singh', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/3574.png", role: 'All-rounder' },
      { name: 'Mohit Rathee', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/1935.png", role: 'Bowler' },
      { name: 'Yash Dayal', image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/978.png", role: 'Bowler' }
],
};
export default playersData;