const teams = [
    {
        id: 1,
        name: 'Chennai Super Kings',
        shortName: 'CSK',
        logo: 'https://documents.iplt20.com/ipl/CSK/logos/Logooutline/CSKoutline.png',
        color: '#ffce00',
        secondaryColor: '#4a4645',
        titles: 5,
        winningYears: [2010, 2011, 2018, 2021, 2023],
        cup: '/cup.jpeg',
        captain: 'Ruturaj Gaikwad',
        coach: 'Stephen Fleming',
        venue: 'M. A. Chidambaram Stadium, Chennai',
        owner: 'Chennai Super Kings Cricket Ltd'
    },
    {
        id: 2,
        name: 'Delhi Capitals',
        shortName: 'DC',
        logo: 'https://documents.iplt20.com/ipl/DC/Logos/LogoOutline/DCoutline.png',
        color: '#C8102E',
        secondaryColor: '#00007f',
        titles: 0,
        winningYears: [],
        captain: 'Axar Patel',
        coach: 'Hemang Badani',
        venue: 'Arun Jaitley Stadium, Delhi',
        owner: 'JSW Sports (50%) and GMR Sports (50%)'
    },
    {
        id: 3,
        name: 'Gujarat Titans',
        shortName: 'GT',
        logo: 'https://documents.iplt20.com/ipl/GT/Logos/Logooutline/GToutline.png',
        color: '#a6a6a6',
        secondaryColor: '#170b3c',
        titles: 1,
        winningYears: [2022],
        cup: '/cup.jpeg',
        captain: 'Shubman Gill',
        coach: 'Ashish Nehra',
        venue: 'Narendra Modi Stadium, Ahmedabad',
        owner: 'CVC Capital Partners'
    },
    {
        id: 4,
        name: 'Kolkata Knight Riders',
        shortName: 'KKR',
        logo: 'https://documents.iplt20.com/ipl/KKR/Logos/Logooutline/KKRoutline.png',
        color: '#FDB913',
        secondaryColor: '#2f1f5a',
        titles: 2,
        winningYears: [2012, 2014],
        cup: '/cup.jpeg',
        captain: 'Ajinkya Rahane',
        coach: 'Chandrakant Pandit',
        venue: 'Eden Gardens, Kolkata',
        owner: 'Red Chillies Entertainment and Mehta Group'
    },
    {
        id: 5,
        name: 'Lucknow Super Giants',
        shortName: 'LSG',
        logo: 'https://documents.iplt20.com/ipl/LSG/Logos/Logooutline/LSGoutline.png',
        color: '#fff',
        secondaryColor: '#5e44aa',
        titles: 0,
        winningYears: [],
        captain: 'Rishabh Pant',
        coach: 'Justin Langer',
        venue: 'BRSABV Ekana Cricket Stadium, Lucknow',
        owner: 'RPSG Group'
    },
    {
        id: 6,
        name: 'Mumbai Indians',
        shortName: 'MI',
        logo: 'https://documents.iplt20.com/ipl/MI/Logos/Logooutline/MIoutline.png',
        color: '#4583bc',
        secondaryColor: '#0a2946',
        titles: 5,
        winningYears: [2013, 2015, 2017, 2019, 2020],
        cup: '/cup.jpeg',
        captain: 'Hardik Pandya',
        coach: 'Mahela Jayawardene',
        venue: 'Wankhede Stadium, Mumbai',
        owner: 'Reliance Industries'
    },
    {
        id: 7,
        name: 'Punjab Kings',
        shortName: 'PBKS',
        logo: 'https://documents.iplt20.com/ipl/PBKS/Logos/Logooutline/PBKSoutline.png',
        color: '#DC1E2B',
        secondaryColor: '#174d7f',
        titles: 0,
        winningYears: [],
        captain: 'Shreyas Iyer',
        coach: 'Ricky Ponting',
        venue: 'Punjab Cricket Association IS Bindra Stadium, Mohali',
        owner: 'Preity Zinta, Ness Wadia, Mohit Burman, and Karan Paul'
    },
    {
        id: 8,
        name: 'Rajasthan Royals',
        shortName: 'RR',
        logo: 'https://documents.iplt20.com/ipl/RR/Logos/Logooutline/RRoutline.png',
        color: '#E60693',
        secondaryColor: '#174d7f',
        titles: 1,
        winningYears: [2008],
        cup: '/cup.jpeg',
        captain: 'Sanju Samson',
        coach: 'Rahul Dravid',
        venue: 'Sawai Mansingh Stadium, Jaipur',
        owner: 'Manoj Badale, Lachlan Murdoch, and others'
    },
    {
        id: 9,
        name: 'Royal Challengers Bangalore',
        shortName: 'RCB',
        logo: 'https://documents.iplt20.com/ipl/RCB/Logos/Logooutline/RCBoutline.png',
        color: '#202427',
        secondaryColor: '#561c12',
        titles: 0,
        winningYears: ["Ee Saala Cup Namde"],
        captain: 'Rajat Patidar',
        coach: 'Andy Flower',
        venue: 'M. Chinnaswamy Stadium, Bengaluru',
        owner: 'United Spirits'
    },
    {
        id: 10,
        name: 'Sunrisers Hyderabad',
        shortName: 'SRH',
        logo: 'https://documents.iplt20.com/ipl/SRH/Logos/Logooutline/SRHoutline.png',
        color: '#b27300',
        secondaryColor: '#425612',
        titles: 1,
        winningYears: [2016],
        cup: '/cup.jpeg',
        captain: 'Pat Cummins',
        coach: 'Daniel Vettori',
        venue: 'Rajiv Gandhi International Cricket Stadium, Hyderabad',
        owner: 'Sun TV Network'
    }
];

export default teams;
